# Generated by Django 4.2.3 on 2023-07-13 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("Visa", "Visa"), ("Mastercard", "Mastercard")],
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EUR", "EUR"), ("RUB", "RUB")],
                        max_length=3,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
