# Generated by Django 4.2.3 on 2023-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_date_of_birth_user_name_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(null=True),
        ),
    ]
